class OneplusNordCE4{
 public static void main(String [] args){
 
	System.out.println("Processor: The Qualcomm Snapdragon 7 Gen 3 chipset not only gives your Nord CE4 silly levels of OnePlus Fast and Smooth performance, but it also guards your battery life and maximizes power efficiency. What's more? You get to experience blazing download speeds up to 5Gbps deliver unceasing mobile gaming, work-from-anywhere productivity, and more");
	System.out.println("Design: OnePlus Nord CE4 comes in 2 colorways - Celadon Marble, a first for Nord and Dark Chrome, our signature variant. Oh, and it’s mega-durable… This phone’s bezel material is so tough, it’s thinking of taking up cage fighting. Seriously, we dropped it 1.5 meters onto marble, and it survived2. That’s tough as nails!");
	System.out.println("Battery & Charging: The most powerful fast charging in Nord history, with 100W SuperVOOC charging and 5500mAh Battery. Handle your low battery woes like a boss with 100W SUPERVOOC fast charging that boosts your phone to 100% power in 30 minutes. Smart Charging 4.0 learns your usage habits to optimize charging and prevent overheating and battery aging. After 10mins charging (from 1%), you get to enjoy · 7.3hrs of video watching (app:YouTube) · 19.7hrs of music listening (app:Spotify) · 10.9hrs of voice calling (app: WhatsApp) · 6.7hrs of social media browsing (app:Instagram) · 3.9hrs of gaming (app:Battlegrounds India)");
	System.out.println("RAM & ROM: No one likes a slow phone, so OnePlus Nord CE4 comes with 8GB of RAM and up to 8GB of virtual RAM expansion to keep your app switching and loading slick and speedy. Plus, you get lots of space for saving evidence of your adventures, with up to 256GB of storage (ROM) and a second SIM card slot that supports microSD cards for expandable storage up to 1TB!");
	System.out.println("Camera: SONY LYT-600 (IMX882) 50MP camera sensor with OIS ensures that you get more stable and clearer pictures, no matter off road or uneven terrains, capture moving subjects and your unshakeable spirit. Further, with flagship-level RAW HDR algorithm, OnePlus Nord CE4 has better photography performance when taking portraits in sunny day.");
}
}